---
name: Test Image Build

on:
  pull_request:
    branches:
      - main
      - master
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "test-image-${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      packages: write # required for pushing the test image to ghcr.io
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }} # required for better experience using pre-releases
          fetch-depth: "0" # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: Build Docker image and test push action
        id: build-to-test
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: |
            ghcr.io/sysdiglabs/sysdig-mcp-server:test

      - name: Test we can execute the docker image
        run: |
          docker run --rm ghcr.io/sysdiglabs/sysdig-mcp-server:test --help | grep "Sysdig MCP Server"

      - name: Scan Docker image
        uses: sysdiglabs/scan-action@v6
        with:
          image-tag: ghcr.io/sysdiglabs/sysdig-mcp-server:test
          sysdig-secure-token: ${{ secrets.SECURE_ENV_MON_API_KEY }}
          sysdig-secure-url: ${{ secrets.SECURE_ENV_MON_ENDPOINT }}
          stop-on-failed-policy-eval: true
          stop-on-processing-error: true
